### PR TITLE
feat(core): exposed promise when config settings loaded

### PR DESCRIPTION
**Pull request by unlight**
** PR Checklist
Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/fulls1z3/ngx-config/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

** PR Type
What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

** What is the current behavior?

Issue Number: #147 

** What is the new behavior?

** Does this PR introduce a breaking change?
```
[ ] Yes
[x] No
```

** Other information

### CODE REVIEW

**Comment by unlight** [comment]
Please merge this to 4.X branch also (and publish new version for angular 4.X)

**Comment by unlight** [comment]
#147

**Comment by fulls1z3** [comment]
@unlight i tried this solution using race conditions and it just fakes the promise completion with empty settings. I'll dig this further in future.

**Comment by unlight** [comment]
Sorry, but I did not get you. Is this solution does not work as expected?
Please, reopen #147 to keep track this feature.

**Pull request closed without merging**
